HallBuddy_Website/HallBuddy_Website/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
    path('admin/', admin.site.urls),
    path('Home/', include('Home.urls')),
    path('', include('authentication.urls')),
    path('guestroom/', include('guestroom.urls')),
    path('Complaints/', include('Complaints.urls')),
    path('Cleaning/', include('Cleaning.urls')),
    path('payments/', include('django_razorpay.urls', namespace="django_razorpay")),
]

HallBuddy_Website/Home/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path ('', views.Make_Homepage, name = 'Home') ,
    path('map', views.map, name = 'map'),
    path('contact', views.contact, name = 'contact'),
    path('shop', views.shop, name = 'shop'),
    path('dues', views.dues, name = 'dues'),
]

HallBuddy_Website/django_razorpay/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name = "django_razorpay"
urlpatterns = [
    path('membership-fee', membership_fee, name="membership_fee"),
    path('get_member_details', get_member_details, name="get_member_details"),
    path('payment-verify', PaymentVerify.as_view(), name="payment_verify"),
    path('payment-success', payment_success, name="payment_success"),
    path('payment-failed', payment_failed, name="payment_failed"),
    path('transactions', transactions, name="transactions"),
    path('manual-transaction', manual_transaction, name="manual_transaction"),
    path('adhoc', addhoc_payment, name="addhoc_payment"),
    path('', transactions, name="index"),
]

HallBuddy_Website/django_razorpay/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone

# Create your models here.


class Member(models.Model):
    name = models.CharField("name", blank=True, max_length=50)
    phone = models.CharField("phone number", blank=True, max_length=20)
    email = models.EmailField("email address", blank=True)
    date_joined = models.DateTimeField("date joined", default=timezone.now)

    def __str__(self):
        return self.name


class Transaction(models.Model):
    ALL = "ALL"
    INCOMING = "INCOMING"
    OUTGOING = "OUTGOING"
    TYPE_CHOICES = (
        (INCOMING, "Incoming"),
        (OUTGOING, "Outgoing"),
    )
    PAYMENT_TYPE_LABEL = [{"label": "All", "value": ALL},
                          {"label": "Incoming", "value": INCOMING},
                          {"label": "Expense", "value": OUTGOING},
                          ]

    payment_type = models.CharField(max_length=15,
                                    choices=TYPE_CHOICES,
                                    default=INCOMING)

    label = models.CharField("label", blank=True, max_length=50)
    amount = models.DecimalField("amount", blank=True, decimal_places=2, max_digits=12)
    data = models.JSONField(blank=True, null=True)
    created_at = models.DateTimeField("date joined", default=timezone.now)

    def __str__(self):
        sign = "-" if self.payment_type == self.OUTGOING else "+"
        return "{}{}".format(sign, self.label)

    @property
    def get_label(self):
        return self.label

    @property
    def get_amount_html(self):
        sign = "<span class='text-danger'>-" if self.payment_type == self.OUTGOING else "<span class='text-success'>+"
        return "{}{}</span>".format(sign, self.amount)

    @property
    def date(self):
        return self.created_at.date


class Balance(models.Model):
    """
    Total current balance
    """
    amount = models.DecimalField("amount", default=0, decimal_places=2, max_digits=12)
    label = models.CharField("label", blank=True, max_length=50)
    updated_at = models.DateTimeField("Updated at", default=timezone.now)

    def __str__(self):
        return str(self.amount) + " | " + str(self.updated_at) + " | " + str(self.label)

    def save(self, *args, **kwargs):
        if not self.pk and Balance.objects.exists():
            raise ValidationError('There is can be only one Balance instance')
        return super(Balance, self).save(*args, **kwargs)


class Organization(models.Model):
    """
    Organization details
    """
    membership_fee = models.DecimalField("membership_fee", default=200, decimal_places=2, max_digits=12, null=True)
    gateway_charges = models.DecimalField("gateway_charges", default=3, decimal_places=2, max_digits=12, null=True)

    updated_at = models.DateTimeField("Updated at", default=timezone.now)

    def __str__(self):
        return str(self.membership_fee) + " | " + str(self.updated_at) + " | " + str(self.gateway_charges)

    def save(self, *args, **kwargs):
        if not self.pk and Organization.objects.exists():
            raise ValidationError('There is can be only one Balance instance')
        return super(Organization, self).save(*args, **kwargs)

# # ----------------
# # Create initial object on load
# # ----------------
#
# if not Balance.objects.exists():
#     Balance.objects.create()
#
# if not Organization.objects.exists():
#     Organization.objects.create()

HallBuddy_Website/django_razorpay/views.py
import json
import datetime
import time
from decimal import Decimal

from dateutil.relativedelta import relativedelta
from django.conf import settings
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import RedirectView
from django.contrib import messages
from django_razorpay.models import *
from django_razorpay.utils import RazorpayCustom, add_amount_to_total, deduct_amount_from_total
from django.utils.timezone import make_aware
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required


def membership_fee(request):
    members = Member.objects.all().values_list('name', flat=True)
    razorpay_instance = RazorpayCustom()
    if request.method == "POST":
        org = Organization.objects.last()
        if razorpay_instance.is_fee_applicable():
            amount = razorpay_instance.get_amount_with_charges(org.membership_fee)
        else:
            amount = round(org.membership_fee, 2)

        phonenumber = request.POST.get("phonenumber")
        name = request.POST.get("name")
        email = request.POST.get("email")
        existing_member = Member.objects.filter(name=name).first()
        if existing_member and phonenumber and email:
            existing_member.email = email
            existing_member.phone = phonenumber
            existing_member.save()

        if razorpay_instance.use_payment_link():
            return redirect(razorpay_instance.create_payment_link(amount=amount,
                                                                  email=email,
                                                                  name=name,
                                                                  phonenumber=phonenumber,
                                                                  reference_id="membership_fee__"
                                                                               + str(existing_member.id)
                                                                               + "__"))
        else:
            payment_data = razorpay_instance.create_order(amount=amount,
                                                          email=email,
                                                          name=name,
                                                          phonenumber=phonenumber)

            return render(request, "django_razorpay/checkout.html", dict(payment_data=payment_data))
    else:
        use_rz_payment_link = razorpay_instance.use_payment_link() or False
        return render(request, "django_razorpay/membership_fee.html", dict(members=members,
                                                                           use_rz_payment_link=use_rz_payment_link))


def payment_success(request):
    messages.success(request, "Payment successful....")
    return render(request, "django_razorpay/payment_status.html")


def payment_failed(request):
    messages.error(request, "Payment failed !!")
    return render(request, "django_razorpay/payment_status.html")


@csrf_exempt
def get_member_details(request):
    data = json.loads(request.body)
    member = Member.objects.filter(name=data['name']).first()
    member_detail = {"email": member.email, "phonenumber": member.phone}
    return JsonResponse(member_detail)


class PaymentVerify(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        rz = RazorpayCustom()
        if rz.verify_payment(self.request):
            razorpay_payment_id = self.request.GET.get('razorpay_payment_id')
            label = self.request.GET.get('label')
            payment = rz.client.payment.fetch(razorpay_payment_id)
            amount = payment['amount'] / 100

            if rz.use_payment_link():
                payment_link_reference_id = self.request.GET.get('razorpay_payment_link_reference_id')
                razorpay_payment_link_id = self.request.GET.get('razorpay_payment_link_id')
                payment_link = rz.client.payment_link.fetch(razorpay_payment_link_id)
                if 'add_hoc' in payment_link_reference_id:
                    label = payment_link["notes"]["label"]
                elif "membership_fee" in payment_link_reference_id:
                    ids = payment_link_reference_id.split("__")
                    member = Member.objects.filter(id=int(ids[1])).first()
                    label = str(member.name) + "(Fee)"

            else:   # for checkout page
                email = ""
                if payment.get('email'):
                    email = payment.get('email')
                elif payment.get('customer_id'):
                    customer = rz.client.customer.fetch(payment['customer_id'])
                    email = customer["email"]
                member = Member.objects.filter(email=email).first()
                if label:
                    pass
                elif member:
                    label = member.name
                else:
                    label = email

            if rz.is_fee_applicable():
                amount = rz.get_amount_deducting_charges(Decimal(amount))

            if Transaction.objects.filter(data__id=razorpay_payment_id).exists():
                return reverse("django_razorpay:payment_failed")

            add_amount_to_total(amount, razorpay_payment_id)
            Transaction.objects.create(amount=amount,
                                       data=payment,
                                       label=label,
                                       payment_type=Transaction.INCOMING)
            messages.success(self.request, "Payment successful....")
            return reverse("django_razorpay:transactions")
        else:
            return reverse("django_razorpay:payment_failed")


def transactions(request):
    total_balance = Balance.objects.last().amount
    month_selected = request.GET.get("month")
    payment_type_selected = request.GET.get("payment-type")
    last_few_months = []
    now = timezone.now()
    month_value_format = "%b-%Y"

    if month_selected:
        current_month = month_selected
    else:
        current_month = now.strftime(month_value_format)

    current_month_dt = datetime.datetime.strptime(current_month, month_value_format)
    for i in range(10):
        __month = now - relativedelta(months=i)
        last_few_months.append({"label": __month.strftime("%b %Y"), "value": __month.strftime(month_value_format)})

    transactions_qs = Transaction.objects.filter(created_at__month=current_month_dt.month,
                                                 created_at__year=current_month_dt.year,
                                                 ).order_by('-created_at')
    if not payment_type_selected or payment_type_selected == Transaction.ALL:
        current_payment_type = Transaction.ALL
        transactions = transactions_qs.all()
    else:
        current_payment_type = payment_type_selected
        transactions = transactions_qs.filter(payment_type=payment_type_selected,
                                                  ).all()

    return render(request, "django_razorpay/transactions.html", {"transactions": transactions,
                                                                 "total_balance": total_balance,
                                                                 "last_few_months": last_few_months,
                                                                 "current_month": current_month,
                                                                 "payment_types": Transaction.PAYMENT_TYPE_LABEL,
                                                                 "current_payment_type": current_payment_type
                                                                 })


@login_required
@staff_member_required
def manual_transaction(request):
    if request.method == "POST":
        payment_type = request.POST.get("payment_type")
        label = request.POST.get("label")
        amount = request.POST.get("amount")
        date_dt = datetime.datetime.strptime(request.POST.get("date"), '%d/%m/%Y')
        if payment_type == Transaction.INCOMING:
            add_amount_to_total(amount, "manual-transaction")
        elif payment_type == Transaction.OUTGOING:
            deduct_amount_from_total(amount, "manual-transaction")
        else:
            raise ValidationError("Please provide payment type")
        Transaction.objects.create(amount=amount,
                                   label=label,
                                   payment_type=payment_type,
                                   created_at=make_aware(date_dt))

        messages.success(request, "Transaction added....")
    return render(request, "django_razorpay/manual_transaction.html",
                  {"payment_types": Transaction.PAYMENT_TYPE_LABEL[1:]})


def addhoc_payment(request):
    if request.method == "POST":
        razorpay_instance = RazorpayCustom()
        if razorpay_instance.is_fee_applicable():
            amount = razorpay_instance.get_amount_with_charges(Decimal(request.POST.get("amount")))
        else:
            amount = round(Decimal(request.POST.get("amount")), 2)

        if razorpay_instance.use_payment_link():
            return redirect(razorpay_instance.create_payment_link(amount=amount,
                                                                  label=request.POST.get("label"),
                                                                  reference_id="add_hoc_"))
        else:
            return render(request, "django_razorpay/checkout.html",
                          dict(payment_data=RazorpayCustom().create_order(amount=amount,
                                                                          name=request.POST.get("label"))))
    else:
        return render(request, "django_razorpay/adhoc_payment.html")

HallBuddy_Website/django_razorpay/templates/django_razorpay/adhoc_payment.html
{% extends "django_razorpay/base.html" %}
{% load static %}
{% block head %}{% endblock %}
{% block title %}Adhoc Payment{% endblock %}

{% block main %}
<main>
    <div class="py-5 text-center">
      <h2>RazorPay</h2>
      <p class="lead">Payments made Easier</p>
    </div>
    <div class="row g-5 align-items-center justify-content-center">
      <div class="col-md-7 col-lg-5">
          <div class="row">
          <div class="col-12">
              {% for message in messages %}
              <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
              <strong>{{ message }}</strong>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
              {% endfor %}
            </div>

          </div>
        <h4 class="mb-3">Provide details</h4>
        <form method="POST">
          {% csrf_token %}
          <div class="row g-3">
            <div class="col-12">
              <label for="name" class="form-label">Due Description, Name, Roll No. </label>
              <input type="text" class="form-control border border-primary" id="name" name="label" placeholder="Example: Mess dues, Ravi Teja, 225958" required>

            </div>
              <div class="col-12">
              <label for="amount" class="form-label ">Amount</label>
              <input type="text" class="form-control border border-primary" id="amount" name="amount" placeholder="Example: 200" required>
            </div>
          <hr class="my-4">
          <button class="w-100 btn btn-primary btn-lg" type="submit">Proceed to Pay</button>
          </div>
        </form>
      </div>
    </div>
  </main>
{% endblock %}
{% block js %}
<script>
  $(document).ready(function(){

  });
</script>
{% endblock %}

HallBuddy_Website/django_razorpay/templates/django_razorpay/base.html
{% load static %}
{% load dj_razorpay %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>{% block title %}{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/checkout/">
      <!-- Bootstrap core CSS -->
    <link href="{% static 'django_razorpay/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'django_razorpay/css/bootstrap-select.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    {% block head %}{% endblock %}
  </head>
  <body class="bg-light">
  <div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <img class="bi me-2" width="160" height="80" src={% static '\django_razorpay/hallbuddy1-1100h.png' %} >
      </a>
    </header>
  </div>
<div class="container">
  {% block main %}{% endblock %}

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2024-2031 {% organization_name %}</p>
<!--    <ul class="list-inline">-->
<!--      <li class="list-inline-item"><a href="#">Privacy</a></li>-->
<!--      <li class="list-inline-item"><a href="#">Terms</a></li>-->
<!--      <li class="list-inline-item"><a href="#">Support</a></li>-->
<!--    </ul>-->
  </footer>
</div>


<script src="{% static 'django_razorpay/js/bootstrap.bundle.min.js' %}"></script>

<script src="{% static 'django_razorpay/js/jquery.min.js' %}"></script>
<script src="{% static 'django_razorpay/js/bootstrap-select.min.js' %}"></script>
{% block js %}{% endblock %}

  </body>
</html>

HallBuddy_Website/django_razorpay/templates/django_razorpay/checkout.html
{% extends "django_razorpay/base.html" %}
{% block title %}Checkout{% endblock %}
{% load static %}
{% block main %}
<div class="container pb-5 mb-sm-4">
      <div class="pt-5">
        <div class="card py-3 mt-sm-3">
          <div class="card-body text-center">
            <h2 class="h4 pb-3">Pay securely</h2>
              Amount: <br>
              <h3 class="font-weight-normal text-center">

                 <span class="text-accent pt-2">
                   {{payment_data.currency|upper}}  {{payment_data.amount}}
                 </span>
            </h3>

              <a class="btn btn-primary mt-3" id="rzp-button1" ><i class="czi-card"></i>&nbsp;Click to Pay</a>
              <a href="{% url 'django_razorpay:membership_fee' %}" class="btn btn-secondary mt-3 mr-3">Cancel</a>
          </div>
        </div>
      </div>
    </div>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>
    var options = {
        "key": "{{payment_data.gateway.key}}", // Enter the Key ID generated from the Dashboard
        "amount": "{{payment_data.amount}}",
        "order_id": "{{payment_data.order_id}}",
        "currency": "{{payment_data.currency|upper}}",
        "name": "{{payment_data.organization_name}}",
        "description": "{{payment_data.description}}",
        "image": "{{payment_data.organization_logo}}",
        "handler": function (response){
               window.location.href = "{% url 'django_razorpay:payment_verify' %}?razorpay_payment_id=" + response.razorpay_payment_id + '&&razorpay_order_id=' + response.razorpay_order_id + '&&razorpay_signature='+response.razorpay_signature+ '&&label={{payment_data.name}}';
        },
        "prefill": {
            "name": "{{payment_data.name}}",
            "email": "{{payment_data.email}}",
            "contact": "+91{{payment_data.phonenumber}}"
        },

        "theme": {
            "color": "#009EF7"
        }
    };
    var rzp1 = new Razorpay(options);
    rzp1.on('payment.failed', function (response){
        if(response.razorpay_payment_id){
            window.location.href = "{% url 'django_razorpay:payment_failed' %}";
        }
        else{
            alert("sometrhing");
        }
    });
    document.getElementById('rzp-button1').onclick = function(e){
        rzp1.open();
        e.preventDefault();
    }
    </script>
{% endblock %}
{% block js %}
{{block.super}}
<script>
     $(window).on('load', function() {
        $('#rzp-button1').click();
    });
</script>
{% endblock %}

HallBuddy_Website/django_razorpay/templates/django_razorpay/manual_transaction.html
{% extends "django_razorpay/base.html" %}
{% load static %}
{% block head %}
<link href="{% static 'django_razorpay/css/bootstrap-datepicker.min.css' %}" rel="stylesheet">
{% endblock %}
{% block title %}Manual transaction{% endblock %}

{% block main %}
<main>
    <div class="py-5 text-center">
      <h2>Manual payment transaction</h2>
      <p class="lead">Add a manual payment transaction for incoming or expense</p>
    </div>
    <div class="row g-5 align-items-center justify-content-center">
      <div class="col-md-7 col-lg-5">
          <div class="row">
          <div class="col-12">
              {% for message in messages %}
              <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
              <strong>{{ message }}</strong>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
              {% endfor %}
            </div>

          </div>
        <h4 class="mb-3">Payment details</h4>
        <form method="POST">
          {% csrf_token %}
          <div class="row g-3">
              <div class="col-12">
                  <label for="name" class="form-label">Select Transaction type</label>
                  <select class="form-select form-label" id="paymentTypeSelect" name="payment_type" required>
                      <option value="" selected disabled>-- Select Payment type --</option>
                      {% for payment_type in payment_types %}
                        <option value="{{payment_type.value}}" >{{payment_type.label}}</option>
                    {% endfor %}
                    </select>
              </div>
            <div class="col-12">
              <label for="name" class="form-label">Label / Description</label>
              <input type="text" class="form-control border border-primary" id="name" name="label" placeholder="Provide the description" required>

            </div>
              <div class="col-12">
              <label for="date" class="form-label ">Amount</label>
              <input type="text" class="form-control border border-primary" id="amount" name="amount" placeholder="Example: 200" required>
            </div>
            <div class="col-12">
              <label for="date" class="form-label ">Date</label>
              <input type="text" class="form-control border border-primary date" id="date" name="date" placeholder="Example: 24/04/2022">
            </div>

          <hr class="my-4">
          <button class="w-100 btn btn-primary btn-lg" type="submit">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </main>
{% endblock %}
{% block js %}
<script src="{% static 'django_razorpay/js/bootstrap-datepicker.min.js' %}"></script>
<script>
  $(document).ready(function(){
         $('.date').datepicker({format: 'dd/mm/yyyy'});
  });
</script>
{% endblock %}

HallBuddy_Website/django_razorpay/templates/django_razorpay/membership_fee.html
{% extends "django_razorpay/base.html" %}
{% load static %}
{% block head %}{% endblock %}
{% block title %}Membership Fee Payment{% endblock %}

{% block main %}
<main>
    <div class="py-5 text-center">
      <h2>Membership Fee Payment</h2>
      <p class="lead">This payment is for member only (Using Razorpay)</p>
    </div>
    <div class="row g-5 align-items-center justify-content-center">
      <div class="col-md-7 col-lg-5">
          <div class="row">
          <div class="col-12">
              {% for message in messages %}
              <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
              <strong>{{ message }}</strong>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
              {% endfor %}
            </div>

          </div>
        <h4 class="mb-3">Member details</h4>
        <form method="POST">
          {% csrf_token %}
          <div class="row g-3">
            <div class="col-12">
              <label for="firstName" class="form-label">Name</label>
                <select class="selectpicker form-control border border-primary" data-live-search="true" data-container="body" name="name">
                  <option data-tokens="" disabled selected> -- Search and select your Name -- </option>
                  {% for member in members %}
                  <option data-tokens="{{member}}">{{member}}</option>
                  {% endfor %}

                </select>
            {% if not use_rz_payment_link %}
            </div>
              <div class="col-12">
              <label for="phonenumber" class="form-label ">Phone Number</label>
              <input type="text" class="form-control border border-primary" id="phonenumber" name="phonenumber" placeholder="Example: 9854785478" required>
            </div>
            <div class="col-12">
              <label for="email" class="form-label">Email <span class="text-muted">(Optional)</span></label>
              <input type="email" class="form-control border border-primary" id="email" placeholder="you@example.com" name="email" required>
            </div>
              {% endif %}

          <hr class="my-4">
          <button class="w-100 btn btn-primary btn-lg" type="submit">Continue to checkout</button>
          </div>
        </form>
      </div>
    </div>
  </main>
{% endblock %}
{% block js %}
<script>
  $(document).ready(function(){
  $('.selectpicker').on('changed.bs.select', function (e) {
      var selected = e.target.value;
      let data = {'name': selected, 'csrfmiddlewaretoken': '{{ csrf_token }}'}
      let url = "{% url 'django_razorpay:get_member_details' %}";
      fetch(url, { method: 'POST', body: JSON.stringify(data),
      headers: { 'Accept': 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
       }
      })
        .then(Result => Result.json())
        .then(resp_data => {
            if(resp_data.email !== undefined){
              document.getElementById("email").value = resp_data.email;
            }
            if(resp_data.phonenumber !== undefined){
              document.getElementById("phonenumber").value = resp_data.phonenumber;
            }
        })
        .catch(errorMsg => { console.log(errorMsg); });
  });

  });
</script>
{% endblock %}

HallBuddy_Website/django_razorpay/templates/django_razorpay/payment_status.html
{% extends "django_razorpay/base.html" %}
{% load static %}
{% block title %}Payment status{% endblock %}
{% block head %}{% endblock %}
{% block main %}
<main>
    <div class="row g-5 align-items-center justify-content-center">
      <div class="col-md-7 col-lg-5">
          <div class="row">
          <div class="col-12">
              {% for message in messages %}
              <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
              <strong>{{ message }}</strong>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
              {% endfor %}
            </div>

          </div>

      </div>
    </div>
  </main>
{% endblock %}
{% block js %}
<script>
  $(document).ready(function(){

  });
</script>
{% endblock %}